---
application:
  name: "gameserver-rust"
  project: "test"
  organization: "QoveryCommunity"
databases:
- type: "REDIS"
  name: "redis"
- type: "MYSQL"
  name: "mysql"
routers:
- name: "main-gameserver-rust"
  routes:
  - application_name: "gameserver-rust"
    paths:
    - "/*"
