[package]
name = "tools"
version = "0.1.0"
authors = ["reison <tijay830@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3 #release
lto = true
codegen-units = 1

#[[bin]] # 用来运行 HelloWorld gRPC 服务器的可执行文件
#name = "helloworld-server"
#path = "src/rpc_server.rs"

#[[bin]] # 用来运行 HelloWorld gRPC 客户端的可执行文件
#name = "helloworld-client"
#path = "src/rpc_client.rs"

[dependencies]
num_cpus="1.10.1"
threadpool="1.8.1"
simplelog = "0.10.0"
log="0.4"
futures = "0.3"
serde_json = "1.0"
serde = {version="1.0",features = ["derive"]}
lazy_static = "1.4.0"
protobuf="2.23.0"
protoc-rust="2.23.0"
async-std = "1.7"
http-types = "2.11.1"
async-h1 = "2.3.2"
net2 = "0.2.33"
redis = "0.20"
byteorder = "1.3.4"
anyhow = "1.0.31"
crossbeam ="0.8"
rayon = "1.3.1"
num_enum = "0.5.1"
async-trait = "0.1.41"
chrono = "0.4"
tonic = "0.4"
prost = "0.7"
tonic-build = "0.4"
mio = {version="0.7",features = ["os-poll", "tcp"]}
tokio = "1.1"
rand = "0.8"
[build-dependencies]
tonic-build = "0.4"